apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: my-container
          image: djninjatv/todolist:v1.7 # V1.7 first deployment of react
          ports:
            - containerPort: 80
          env:
            - name: API_URL # Api URL for debugging purposes
              value: "34.123.254.209"
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: todolist
